/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frminicio;


import flogica.conexion;
import flogica.f_accesorios;
import flogica.f_apertura;
import flogica.f_arqueo;
import flogica.f_estados;
import flogica.f_movimiento;
import flogica.f_tipofactura;
import flogica.ftrabajador;
import static frminicio.frmarqueo.jTfmontoa;
import groovy.sql.Sql;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javafx.util.converter.LocalDateTimeStringConverter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.orm.ibatis.SqlMapClientCallback;
import vdatos.vaccesorios;
import vdatos.vaperturar;
import vdatos.varqueo;
import vdatos.vmovimiento;

/**
 *
 * @author justi 
 */
public class frmaperturar extends javax.swing.JInternalFrame{
    // se usa esta para mostrar la hora actual en el sistema al ejecutar formulario
    Calendar  fecha_actual = new GregorianCalendar();

    /**
     * Creates new form frmtipodocumento
     */
    public frmaperturar() {
        initComponents();
        mostrar("");
        inhabilitar();
        // se usa tambien para mostrar la hora actual
        jDatemovi.setCalendar(fecha_actual);
    }
    
    private String accion = "guardar";
     public static int idUsuario;
   
//    void ocultar_columnas(){
//        jTListado.getColumnModel().getColumn(0).setMaxWidth(0);
//        jTListado.getColumnModel().getColumn(0).setMinWidth(0);
//        jTListado.getColumnModel().getColumn(0).setPreferredWidth(0);
//        
//        jTListado.getColumnModel().getColumn(1).setMaxWidth(0);
//        jTListado.getColumnModel().getColumn(1).setMinWidth(0);
//        jTListado.getColumnModel().getColumn(1).setPreferredWidth(0);
//        
//        jTListado.getColumnModel().getColumn(3).setMaxWidth(0);
//        jTListado.getColumnModel().getColumn(3).setMinWidth(0);
//        jTListado.getColumnModel().getColumn(3).setPreferredWidth(0);
//    }
    
    void inhabilitar (){
        jTFidtipodoc.setVisible(false);
    
        jTfmonto.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBCancelar.setEnabled(false);
       
        jTFTrabajador.setEnabled(false);
       jTFidTrabajador.setEnabled(false);
        jDatemovi.setEnabled(false);
       
    }
    
    void habilitar (){
        jTFidtipodoc.setVisible(false);
       jTfmonto.setEnabled(true);
     
 jDatemovi.setEnabled(false);
   
        jBGuardar.setEnabled(true);
        jBCancelar.setEnabled(true);
       
       jTFTrabajador.setEnabled(false);
       jTFidTrabajador.setEnabled(false);
        jTfmonto.requestFocus();
    }
    
    void mostrar (String buscar){
        try {
            DefaultTableModel modelo;
            f_apertura func =new f_apertura();
       
           
            
//            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jTFidtipodoc = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jTfmonto = new javax.swing.JTextField();
        jLNumero5 = new javax.swing.JLabel();
        jLNumero3 = new javax.swing.JLabel();
        jDatemovi = new com.toedter.calendar.JDateChooser();
        jLDescripcion1 = new javax.swing.JLabel();
        jTFidTrabajador = new javax.swing.JTextField();
        jTFTrabajador = new javax.swing.JTextField();
        jBSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apertura de Caja");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de movimiento"));

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/escribir.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/guarde.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancelar-icono-9428-32.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jTfmonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfmontoActionPerformed(evt);
            }
        });

        jLNumero5.setText("Monto ");

        jLNumero3.setText("Fecha aperturar");

        jDatemovi.setDateFormatString("dd/MM/yyyy HH:mm:ss");

        jLDescripcion1.setText("Trabajador:");

        jTFidTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidTrabajadorActionPerformed(evt);
            }
        });

        jTFTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTrabajadorActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLDescripcion1)
                        .addGap(28, 28, 28)
                        .addComponent(jTFidTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jTFTrabajador))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNumero3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDatemovi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTfmonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBNuevo)
                        .addGap(21, 21, 21)
                        .addComponent(jBGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCancelar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFidtipodoc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTFidtipodoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBSalir)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFidTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDatemovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBGuardar)
                            .addComponent(jBCancelar)
                            .addComponent(jBNuevo))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        jTfmonto.requestFocus();
        jBGuardar.setText("Guardar");
        accion="guardar";
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
       
          // jTFidReserva.setText(jTListado.getValueAt(fila, 0).toString());
        
        if(jTfmonto.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar el monto");
            jTfmonto.requestFocus();
            return;
        }
        
        
    
         
         vaperturar dts = new vaperturar();
        f_apertura func = new f_apertura();
        //f_arqueo a = new f_arqueo();
        
     
        //ftrabajador ft = new ftrabajador();
        
        Calendar fecha = Calendar.getInstance();
        Calendar cal;
       
       // java.sql.Date sqlDate = new java.sql.Date(jDatea.getTimeInMillis());
      
   String año= Integer.toString(fecha.get(Calendar.YEAR));
   String mes= Integer.toString(fecha.get(Calendar.MONTH));
   String dia= Integer.toString(fecha.get(Calendar.DATE));
   
   String jDatea = año+"_"+mes+"_"+dia;
          
   String hora=Integer.toString(fecha.get(Calendar.HOUR_OF_DAY));
   String minuto=Integer.toString(fecha.get(Calendar.MINUTE));
   
   String horacomp = hora+":"+minuto;
        
        //cal = jDatea.getCalendar();
//        d = cal.get(Calendar.DAY_OF_MONTH);
//        m = cal.get(Calendar.MONTH);
//        a = cal.get(Calendar.YEAR) - 1900;
//       dts.getFechaaper();
//   String año= Integer.toString(fecha.get(Calendar.YEAR));
//   String mes= Integer.toString(fecha.get(Calendar.MONTH));
//   String dia= Integer.toString(fecha.get(Calendar.DATE));
//   
//   String jDatea = año+"_"+mes+"_"+dia;
//          
//   String hora=Integer.toString(fecha.get(Calendar.HOUR_OF_DAY));
//   String minuto=Integer.toString(fecha.get(Calendar.MINUTE));
//   
//   String horacomp = hora+":"+minuto;
        //int d,m,a;
//        cal = jDater.getCalendar();
//        d = cal.get(Calendar.DAY_OF_MONTH);
//        m = cal.get(Calendar.MONTH);
//        a = cal.get(Calendar.YEAR) - 1900;
//         dts.setFechacierre(new Date(a,m,d));
       

        
       
          
    
       dts.setIdtipotrabajador(idUsuario);
      
        
        dts.setMontoaper(Integer.parseInt(jTfmonto.getText()));
      
      
     
      
        
        

        if (accion.equals("guardar")) {
            if(func.insertar(dts)){
                JOptionPane.showMessageDialog(rootPane, "Movimiento fue registrado satisfactoriamete!");
                mostrar("");
                inhabilitar();
            }
        }
        else if (accion.equals("editar")) {
            dts.setIdaapertura(Integer.parseInt(jTFidtipodoc.getText()));
            dts.setIdtipotrabajador(Integer.parseInt(jTFidTrabajador.getText()));
           // dts.setIdarqueo(Integer.parseInt(jTFidArqueo.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Movimiento fue editado satisfactoriamente!");
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        mostrar("");
        inhabilitar();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTfmontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfmontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfmontoActionPerformed

    private void jTFidTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidTrabajadorActionPerformed

    private void jTFTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTrabajadorActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmaperturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmaperturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmaperturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmaperturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmaperturar().setVisible(true);
            }
        });
    }
//    public boolean ActualizarStock(int cant,String cod){
//        for (int i = 0; i < jTListado.getRowCount(); i++) {
//            int id = Integer.parseInt(jTListado.getValueAt(i, 0).toString());
//            int cantidad = Integer.parseInt(jTListado.getValueAt(i, 2).toString());
//            //cantidad = f_accesorios.(id);
////            int StockActual = pro.getStock() - cant;
////            Vdao.ActualizarStock(StockActual, id);
//
//        }
//        return false;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private com.toedter.calendar.JDateChooser jDatemovi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLDescripcion1;
    private javax.swing.JLabel jLNumero3;
    private javax.swing.JLabel jLNumero5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTFTrabajador;
    public static javax.swing.JTextField jTFidTrabajador;
    private javax.swing.JTextField jTFidtipodoc;
    public static javax.swing.JTextField jTfmonto;
    // End of variables declaration//GEN-END:variables

    
}
