/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frminicio;


import flogica.conexion;
import flogica.f_accesorios;
import flogica.f_arqueo;
import flogica.f_estados;
import flogica.f_movimiento;
import flogica.f_tipofactura;
import flogica.ftrabajador;
import static frminicio.frmarqueo.jTfmontoa;
import groovy.sql.Sql;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javafx.util.converter.LocalDateTimeStringConverter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.orm.ibatis.SqlMapClientCallback;
import vdatos.vaccesorios;
import vdatos.varqueo;
import vdatos.vmovimiento;

/**
 *
 * @author justi 
 */
public class frmmovimiento extends javax.swing.JInternalFrame{
   // Calendar  fecha_actual = new GregorianCalendar();

    /**
     * Creates new form frmtipodocumento
     */
    public frmmovimiento() {
        initComponents();
        mostrar("");
        inhabilitar();
        //jDatea.setCalendar(fecha_actual);
    }
    
    private String accion = "guardar";
     public static int idUsuario;
     public static int idArqueo;
    void ocultar_columnas(){
        jTListado.getColumnModel().getColumn(0).setMaxWidth(0);
        jTListado.getColumnModel().getColumn(0).setMinWidth(0);
        jTListado.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        jTListado.getColumnModel().getColumn(1).setMaxWidth(0);
        jTListado.getColumnModel().getColumn(1).setMinWidth(0);
        jTListado.getColumnModel().getColumn(1).setPreferredWidth(0);
        
        jTListado.getColumnModel().getColumn(3).setMaxWidth(0);
        jTListado.getColumnModel().getColumn(3).setMinWidth(0);
        jTListado.getColumnModel().getColumn(3).setPreferredWidth(0);
    }
    
    void inhabilitar (){
        jTFidtipodoc.setVisible(false);
    
        jTfmonto.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBCancelar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jTfdescri.setEnabled(false);
        jTFTrabajador.setEnabled(false);
       jTFidTrabajador.setEnabled(false);
       
    }
    
    void habilitar (){
        jTFidtipodoc.setVisible(false);
       jTfmonto.setEnabled(true);
     
        jTfdescri.setEnabled(true);
   
        jBGuardar.setEnabled(true);
        jBCancelar.setEnabled(true);
        jBEliminar.setEnabled(true);
       jTFTrabajador.setEnabled(false);
       jTFidTrabajador.setEnabled(false);
        jTfmonto.requestFocus();
    }
    
    void mostrar (String buscar){
        try {
            DefaultTableModel modelo;
            f_movimiento func =new f_movimiento();
            //f_arqueo a = new f_arqueo();
            f_tipofactura fe = new f_tipofactura();
            //ftrabajador ft = new ftrabajador();
            modelo = func.mostrar(buscar);
            fe.cargarComboFactura(jCfactura);
          
            
            jTListado.setModel(modelo);
            ocultar_columnas();
            jLRegistros.setText("Total Registros " + Integer.toString(func.totalregistros));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jTFidtipodoc = new javax.swing.JTextField();
        jLNumero3 = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jTfmonto = new javax.swing.JTextField();
        jLNumero5 = new javax.swing.JLabel();
        jLNumero4 = new javax.swing.JLabel();
        jCfactura = new javax.swing.JComboBox<>();
        jDatemovi = new com.toedter.calendar.JDateChooser();
        jLNumero7 = new javax.swing.JLabel();
        jTfdescri = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTListado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTFBuscar = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLRegistros = new javax.swing.JLabel();
        txtarqueo = new javax.swing.JTextField();
        jLNumero6 = new javax.swing.JLabel();
        jLDescripcion1 = new javax.swing.JLabel();
        jTFidTrabajador = new javax.swing.JTextField();
        jTFTrabajador = new javax.swing.JTextField();
        jTFidArqueo = new javax.swing.JTextField();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimiento");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de movimiento"));

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/escribir.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/guarde.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLNumero3.setText("Fecha Movimiento");

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancelar-icono-9428-32.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jTfmonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfmontoActionPerformed(evt);
            }
        });

        jLNumero5.setText("Monto ");

        jLNumero4.setText("TipoFactura");

        jDatemovi.setDateFormatString("dd/MM/yyyy HH:mm:ss");

        jLNumero7.setText("Descripcion");

        jTfdescri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfdescriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jCfactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNumero3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfdescri, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDatemovi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTfmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFidtipodoc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTFidtipodoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfdescri, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDatemovi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNumero3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBGuardar)
                    .addComponent(jBCancelar))
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de movimiento....."));

        jTListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTListadoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTListado);

        jLabel2.setText("Buscar:");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLRegistros.setText("Registros");

        jLNumero6.setText("Arqueo");

        jLDescripcion1.setText("Trabajador:");

        jTFidTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidTrabajadorActionPerformed(evt);
            }
        });

        jTFTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTrabajadorActionPerformed(evt);
            }
        });

        jTFidArqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFidArqueoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTFidArqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtarqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLDescripcion1)
                .addGap(29, 29, 29)
                .addComponent(jTFidTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTFTrabajador)
                .addGap(209, 209, 209))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar)
                    .addComponent(jBEliminar)
                    .addComponent(jBSalir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFidTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtarqueo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFidArqueo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLNumero6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        jTfmonto.requestFocus();
        jBGuardar.setText("Guardar");
        accion="guardar";
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
       
          // jTFidReserva.setText(jTListado.getValueAt(fila, 0).toString());
         if(jTfdescri.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar el monto");
            jTfdescri.requestFocus();
            return;
        }
        if(jTfmonto.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar el monto");
            jTfmonto.requestFocus();
            return;
        }
        
        
    
         
         vmovimiento dts = new vmovimiento();
        f_movimiento func = new f_movimiento();
        //f_arqueo a = new f_arqueo();
         f_tipofactura fe = new f_tipofactura();
     
        //ftrabajador ft = new ftrabajador();
        
        Calendar fecha = Calendar.getInstance();
        Calendar cal;
       
       // java.sql.Date sqlDate = new java.sql.Date(jDatea.getTimeInMillis());
      
   String año= Integer.toString(fecha.get(Calendar.YEAR));
   String mes= Integer.toString(fecha.get(Calendar.MONTH));
   String dia= Integer.toString(fecha.get(Calendar.DATE));
   
   String jDatea = año+"_"+mes+"_"+dia;
          
   String hora=Integer.toString(fecha.get(Calendar.HOUR_OF_DAY));
   String minuto=Integer.toString(fecha.get(Calendar.MINUTE));
   
   String horacomp = hora+":"+minuto;
        
        //cal = jDatea.getCalendar();
//        d = cal.get(Calendar.DAY_OF_MONTH);
//        m = cal.get(Calendar.MONTH);
//        a = cal.get(Calendar.YEAR) - 1900;
//       dts.getFechaaper();
//   String año= Integer.toString(fecha.get(Calendar.YEAR));
//   String mes= Integer.toString(fecha.get(Calendar.MONTH));
//   String dia= Integer.toString(fecha.get(Calendar.DATE));
//   
//   String jDatea = año+"_"+mes+"_"+dia;
//          
//   String hora=Integer.toString(fecha.get(Calendar.HOUR_OF_DAY));
//   String minuto=Integer.toString(fecha.get(Calendar.MINUTE));
//   
//   String horacomp = hora+":"+minuto;
        //int d,m,a;
//        cal = jDater.getCalendar();
//        d = cal.get(Calendar.DAY_OF_MONTH);
//        m = cal.get(Calendar.MONTH);
//        a = cal.get(Calendar.YEAR) - 1900;
//         dts.setFechacierre(new Date(a,m,d));
       

        
       
          
        dts.setIdarqueo(idArqueo);
       dts.setIdtipotrabajador(idUsuario);
        dts.setComentario(jTfdescri.getText());
        
        dts.setMonto(Integer.parseInt(jTfmonto.getText()));
       dts.setMonto(Integer.parseInt(txtarqueo.getText()));
       // dts.setIdarqueo(a.obtenerIdArqueo(jCarqueo));
        dts.setIdTipoFactura(fe.obtenerIdFactura(jCfactura));
        //dts.d = new SimpleDateFormat("yyyy-MM-dd");
      //  dts.setFecharecla(new Date(a,m,d));
  
       //SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yy HH:mm:ss"); 
     
      
        
        

        if (accion.equals("guardar")) {
            if(func.insertar(dts)){
                JOptionPane.showMessageDialog(rootPane, "Movimiento fue registrado satisfactoriamete!");
                mostrar("");
                inhabilitar();
            }
        }
        else if (accion.equals("editar")) {
            dts.setIdarqueo(Integer.parseInt(jTFidtipodoc.getText()));
            dts.setIdtipotrabajador(Integer.parseInt(jTFidTrabajador.getText()));
            dts.setIdarqueo(Integer.parseInt(jTFidArqueo.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Movimiento fue editado satisfactoriamente!");
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        mostrar("");
        inhabilitar();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTListadoMouseClicked
        // TODO add your handling code here:
        jBGuardar.setText("Editar");
        habilitar();
        jBEliminar.setEnabled(true);
        accion = "editar";
        
        int fila = jTListado.rowAtPoint(evt.getPoint());
        jTListado.setBackground(new Color(203, 159, 41));
        jTListado.setForeground(Color.WHITE); 
        jTFidtipodoc.setText(jTListado.getValueAt(fila, 0).toString());
        jTFidTrabajador.setText(jTListado.getValueAt(fila, 1).toString());
        jTFTrabajador.setText(jTListado.getValueAt(fila, 2).toString());
        jTFidArqueo.setText(jTListado.getValueAt(fila, 3).toString());
        txtarqueo.setText(jTListado.getValueAt(fila, 4).toString());
         jTfdescri.setText(jTListado.getValueAt(fila, 5).toString());
        jTfmonto.setText(jTListado.getValueAt(fila, 6).toString());
        
      //  txtcodigo.setText(jTListado.getValueAt(fila, 2).toString());
     
     
       //jDatea.setDate((jTListado.getValueAt(fila, 3).toString()));
        
       // jDater.setDateFormatString((jTListado.getValueAt(fila, 4).toString()));
       
        jCfactura.setSelectedItem(jTListado.getValueAt(fila, 7).toString());

    }//GEN-LAST:event_jTListadoMouseClicked

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        mostrar(jTFBuscar.getText());
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        if (!jTFidtipodoc.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de eliminar los arqueo ?", "Confirmar", 2);

            if (confirmacion == 0) {
                f_movimiento func = new f_movimiento();
                vmovimiento dts = new vmovimiento();

                dts.setIdarqueo(Integer.parseInt(jTFidtipodoc.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTfmontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfmontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfmontoActionPerformed

    private void jTFidTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidTrabajadorActionPerformed

    private void jTFTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTrabajadorActionPerformed

    private void jTfdescriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfdescriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfdescriActionPerformed

    private void jTFidArqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFidArqueoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFidArqueoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmovimiento().setVisible(true);
            }
        });
    }
//    public boolean ActualizarStock(int cant,String cod){
//        for (int i = 0; i < jTListado.getRowCount(); i++) {
//            int id = Integer.parseInt(jTListado.getValueAt(i, 0).toString());
//            int cantidad = Integer.parseInt(jTListado.getValueAt(i, 2).toString());
//            //cantidad = f_accesorios.(id);
////            int StockActual = pro.getStock() - cant;
////            Vdao.ActualizarStock(StockActual, id);
//
//        }
//        return false;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCfactura;
    private com.toedter.calendar.JDateChooser jDatemovi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLDescripcion1;
    private javax.swing.JLabel jLNumero3;
    private javax.swing.JLabel jLNumero4;
    private javax.swing.JLabel jLNumero5;
    private javax.swing.JLabel jLNumero6;
    private javax.swing.JLabel jLNumero7;
    private javax.swing.JLabel jLRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFBuscar;
    public static javax.swing.JTextField jTFTrabajador;
    public static javax.swing.JTextField jTFidArqueo;
    public static javax.swing.JTextField jTFidTrabajador;
    private javax.swing.JTextField jTFidtipodoc;
    public static javax.swing.JTable jTListado;
    public static javax.swing.JTextField jTfdescri;
    public static javax.swing.JTextField jTfmonto;
    private javax.swing.JTextField txtarqueo;
    // End of variables declaration//GEN-END:variables

    
}
