/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frminicio;


import flogica.conexion;
import flogica.f_accesorios;
import flogica.f_codigocliente;
import flogica.f_mecanico;
import flogica.f_reparacion;
import flogica.f_modelo;
import flogica.f_tipofactura;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vdatos.vreparacion;

//import static org.apache.poi.hssf.usermodel.HeaderFooter.file;

/**
 *
 * @authorjusti
 */
public class frmreparacion extends javax.swing.JFrame {

    /**
     * Creates new form frmhabitacion
     */
    public frmreparacion() {
        initComponents();
        mostrar("");
        inhabilitar();
    }

    private String accion = "guardar";

    void ocultar_columnas() {
        jTListado.getColumnModel().getColumn(0).setMaxWidth(0);
        jTListado.getColumnModel().getColumn(0).setMinWidth(0);
        jTListado.getColumnModel().getColumn(0).setPreferredWidth(0);
        
       
    }

    void inhabilitar() {
        jTFidhabitacion.setVisible(false);

       
        jCBMODELO.setEnabled(false);
        jTFnombre.setEnabled(false);
        jTFgarantia.setEnabled(false);
        jTFmanodeobra.setEnabled(false);
        jTFmanodeobra.setEnabled(false);
        txtidaccesorios.setEnabled(false);
        txtclientes.setEnabled(false);
        txtidcliente.setEnabled(false);
        txtidmecanico.setEnabled(false);
        txtmecanico.setEnabled(false);
        txtidaccesorios.setEnabled(false);
        txtaccesorios.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBCancelar.setEnabled(false);
        jBEliminar.setEnabled(false);
        //jbreporte.setEnabled(false);
        jTFnombre.setText("");
        jTFidhabitacion.setText("");
        jCBMODELO.setSelectedIndex(-1);
      
       
    }

    void habilitar() {
        jTFidhabitacion.setVisible(false);

       
       jCBMODELO.setEnabled(true);
        jTFnombre.setEnabled(true);
       jTFmanodeobra.setEnabled(true);
       jTFmanodeobra.setEnabled(true);
        txtidaccesorios.setEnabled(false);
        jTFgarantia.setEnabled(true);
        txtclientes.setEnabled(true);
        txtidmecanico.setEnabled(false);
        txtmecanico.setEnabled(true);
        txtidaccesorios.setEnabled(false);
        txtaccesorios.setEnabled(true);

        jBGuardar.setEnabled(true);
        jBCancelar.setEnabled(true);
        jBEliminar.setEnabled(true);
       // jbreporte.setEnabled(true);
        jTFnombre.setText("");
        jTFidhabitacion.setText("");
       
      
        jCBMODELO.setSelectedIndex(-1);
      
       jCbFACTIRA.setSelectedIndex(-1);
        jTFnombre.requestFocus();
    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            f_reparacion func = new f_reparacion();
            
            f_modelo fp = new f_modelo();
            //f_mecanico fm = new f_mecanico();
            //f_codigocliente fc = new f_codigocliente();
            f_tipofactura ft = new f_tipofactura();
            modelo = func.mostrar(buscar);

            jTListado.setModel(modelo);
            ocultar_columnas();
            jLRegistros.setText("Total Registros " + Integer.toString(func.totalregistros));
           // jTFmanodeobra.setText("Total Registros " + Integer.toString(func.jTFtotalpagar1));
         
           
//            fe.cargarComboEstados(jCBEstado);
           fp.cargarComboModelo(jCBMODELO);
           ft.cargarComboFactura(jCbFACTIRA);
          

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTFidhabitacion = new javax.swing.JTextField();
        jLNumero = new javax.swing.JLabel();
        jTFnombre = new javax.swing.JTextField();
        jLPiso = new javax.swing.JLabel();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jCBMODELO = new javax.swing.JComboBox<>();
        jLPiso1 = new javax.swing.JLabel();
        jLPiso2 = new javax.swing.JLabel();
        jLPiso3 = new javax.swing.JLabel();
        jCbFACTIRA = new javax.swing.JComboBox<>();
        jLNumero1 = new javax.swing.JLabel();
        jTFmanodeobra = new javax.swing.JTextField();
        jLNumero2 = new javax.swing.JLabel();
        jTFgarantia = new javax.swing.JTextField();
        txtmecanico = new javax.swing.JTextField();
        txtclientes = new javax.swing.JTextField();
        txtidmecanico = new javax.swing.JTextField();
        btnbuscarmeca = new javax.swing.JToggleButton();
        btnbuscarclientes = new javax.swing.JToggleButton();
        jLPiso4 = new javax.swing.JLabel();
        txtaccesorios = new javax.swing.JTextField();
        btnbuscaraccesorios = new javax.swing.JToggleButton();
        txtidaccesorios = new javax.swing.JTextField();
        txtidcliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTListado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTFBuscar = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jbreporte = new javax.swing.JButton();
        jLRegistros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro a Reparar ");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de reparacion"));

        jLNumero.setText("Problema ");

        jTFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnombreActionPerformed(evt);
            }
        });

        jLPiso.setText("Modelo");

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/escribir.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/guarde.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancelar-icono-9428-32.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jCBMODELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMODELOActionPerformed(evt);
            }
        });

        jLPiso1.setText("Clientes");

        jLPiso2.setText("Mecanico");

        jLPiso3.setText("Tipo Factura");

        jCbFACTIRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbFACTIRAActionPerformed(evt);
            }
        });

        jLNumero1.setText("Mano de obra");

        jTFmanodeobra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFmanodeobraActionPerformed(evt);
            }
        });

        jLNumero2.setText("Garantia");

        jTFgarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFgarantiaActionPerformed(evt);
            }
        });

        txtmecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmecanicoActionPerformed(evt);
            }
        });

        txtclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclientesActionPerformed(evt);
            }
        });

        txtidmecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidmecanicoActionPerformed(evt);
            }
        });

        btnbuscarmeca.setText("...");
        btnbuscarmeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarmecaActionPerformed(evt);
            }
        });

        btnbuscarclientes.setText("...");
        btnbuscarclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarclientesActionPerformed(evt);
            }
        });

        jLPiso4.setText("Accesorios");

        txtaccesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccesoriosActionPerformed(evt);
            }
        });

        btnbuscaraccesorios.setText("...");
        btnbuscaraccesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaraccesoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelar)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtmecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnbuscarmeca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnbuscarclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jCBMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFidhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFmanodeobra, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTFgarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLPiso2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLPiso1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtidmecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLPiso4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtidaccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtaccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnbuscaraccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCbFACTIRA, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLPiso3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTFidhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFmanodeobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFgarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNumero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLPiso2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtidmecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarmeca))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPiso1)
                            .addComponent(txtclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarclientes))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscaraccesorios)
                            .addComponent(jLPiso4)
                            .addComponent(txtidaccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPiso3)
                    .addComponent(jCbFACTIRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBNuevo)
                        .addComponent(jBCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBGuardar)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("reparado guardado"));

        jTListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTListadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTListadoMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTListado);

        jLabel2.setText("Buscar:");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jbreporte.setText("Reportes");
        jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreporteActionPerformed(evt);
            }
        });

        jLRegistros.setText("Total de Registro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBuscar))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBSalir)
                        .addComponent(jBEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbreporte)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236)
                .addComponent(jLRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        if (!jTFidhabitacion.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de eliminar la reparacion?", "Confirmar", 2);

            if (confirmacion == 0) {
                f_reparacion func = new f_reparacion();
                vreparacion dts = new vreparacion();

                dts.setIdreparacion(Integer.parseInt(jTFidhabitacion.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        mostrar(jTFBuscar.getText());
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTListadoMouseClicked
        // TODO add your handling code here:
        jBGuardar.setText("Editar");
        habilitar();
        jBEliminar.setEnabled(true);
        accion = "editar";

        int fila = jTListado.rowAtPoint(evt.getPoint());

        jTFidhabitacion.setText(jTListado.getValueAt(fila, 0).toString());
        txtidaccesorios.setText(jTListado.getValueAt(fila, 1).toString());
        txtclientes.setText(jTListado.getValueAt(fila, 2).toString());
       txtidmecanico.setText(jTListado.getValueAt(fila, 3).toString());
        txtmecanico.setText(jTListado.getValueAt(fila, 4).toString());
        txtidaccesorios.setText(jTListado.getValueAt(fila, 5).toString());
        txtaccesorios.setText(jTListado.getValueAt(fila, 6).toString());
        jTFnombre.setText(jTListado.getValueAt(fila, 7).toString());
        jTFmanodeobra.setText(jTListado.getValueAt(fila, 8).toString());
        jTFgarantia.setText(jTListado.getValueAt(fila, 9).toString());
        
        jCBMODELO.setSelectedItem(jTListado.getValueAt(fila, 10).toString());
        jCbFACTIRA.setSelectedItem(jTListado.getValueAt(fila, 11).toString());
    }//GEN-LAST:event_jTListadoMouseClicked

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jBSalirActionPerformed
    private Connection connection=new conexion().conectar();
    
    private void jbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreporteActionPerformed
        // TODO add your handling code here:
           //Map p =new HashMap();
          // JasperReport  report;
          // JasperPrint print;
          // 
          // try {
          //  report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+
             //       "/src/Reportes/rpHabitaciones.jrxml");  
          //  print=JasperFillManager.fillReport(report, p,connection);
           //    JasperViewer view=new JasperViewer(print,false);
            //   view.setTitle("Reporte de Habitaciones");
            //   view.setVisible(true);
       // } catch (Exception e) {
       //     e.printStackTrace();
      //  }  
    }//GEN-LAST:event_jbreporteActionPerformed

    private void jCBMODELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMODELOActionPerformed
        // TODO add your handling code here:
         jCBMODELO.transferFocus();
    }//GEN-LAST:event_jCBMODELOActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        mostrar("");
        inhabilitar();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        if (txtidaccesorios.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar lo que se reparo");
            txtidaccesorios.requestFocus();
            return;
        }
        if (txtidcliente.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar lo que se reparo");
            txtidcliente.requestFocus();
            return;
        }
        if (txtidmecanico.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar lo que se reparo");
            txtidmecanico.requestFocus();
            return;
        }
        if (jTFnombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar lo que se reparo");
            jTFnombre.requestFocus();
            return;
        }
        if (jTFmanodeobra.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar lo que se reparo");
            jTFmanodeobra.requestFocus();
            return;
        }
        if (jTFgarantia.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar lo que se reparo");
            jTFgarantia.requestFocus();
            return;
        }
        
       
       
        

        vreparacion dts = new vreparacion();
        f_reparacion func = new f_reparacion();

       
        f_modelo fp = new f_modelo();
        f_mecanico fm = new f_mecanico();
        f_codigocliente fc=new f_codigocliente();
        f_tipofactura ft = new f_tipofactura();
        f_accesorios fa= new f_accesorios();
        

        dts.setProblema(jTFnombre.getText());
        dts.setManodeobra(Integer.parseInt(jTFmanodeobra.getText()));
        dts.setGarantia(jTFgarantia.getText());
       
        dts.setIdClientes(Integer.parseInt(txtidaccesorios.getText()));
        dts.setIdmecanico(Integer.parseInt(txtidmecanico.getText()));
        dts.setIdAccesorios(Integer.parseInt(txtidaccesorios.getText()));
        
       
         int seleccionado = jCBMODELO.getSelectedIndex();
         dts.setIdModelo(fp.obtenerIdModelo(jCBMODELO));
        

        dts.setIdTipoFactura(ft.obtenerIdFactura(jCbFACTIRA));
       
        //dts.setIdAccesorios(fm.obtenerIdAccesorios(jCBacc ));
        //////////////////////////////////////////
        

         

        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "Reparacion fue registrada satisfactoriamete!");
                mostrar("");
                inhabilitar();
            }
        } else if (accion.equals("editar")) {
            dts.setIdreparacion(Integer.parseInt(jTFidhabitacion.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El departamento  fue editada satisfactoriamente!");
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        jBGuardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jTFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnombreActionPerformed
        // TODO add your handling code here:
        jTFnombre.transferFocus();
    }//GEN-LAST:event_jTFnombreActionPerformed

    private void jCbFACTIRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbFACTIRAActionPerformed
        // TODO add your handling code here:
           jCbFACTIRA.transferFocus();
    }//GEN-LAST:event_jCbFACTIRAActionPerformed

    private void jTFmanodeobraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFmanodeobraActionPerformed
        // TODO add your handling code here:
           jTFmanodeobra.transferFocus();
    }//GEN-LAST:event_jTFmanodeobraActionPerformed

    private void jTFgarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFgarantiaActionPerformed
        // TODO add your handling code here:
           jTFgarantia.transferFocus();
    }//GEN-LAST:event_jTFgarantiaActionPerformed

    private void txtmecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmecanicoActionPerformed
        // TODO add your handling code here:
           txtmecanico.transferFocus();
    }//GEN-LAST:event_txtmecanicoActionPerformed

    private void txtclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclientesActionPerformed
        // TODO add your handling code here:
           txtclientes.transferFocus();
    }//GEN-LAST:event_txtclientesActionPerformed

    private void btnbuscarmecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarmecaActionPerformed
        // TODO add your handling code here:
        frmvistamecanico form = new frmvistamecanico();
        form.toFront();
        form.setVisible(true);
       
    }//GEN-LAST:event_btnbuscarmecaActionPerformed

    private void btnbuscarclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarclientesActionPerformed
        // TODO add your handling code here:
         frmvistaclientes form = new frmvistaclientes();
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnbuscarclientesActionPerformed

    private void txtaccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccesoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccesoriosActionPerformed

    private void btnbuscaraccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaraccesoriosActionPerformed
        // TODO add your handling code here:
         frmvistaaccesorios form = new frmvistaaccesorios();
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnbuscaraccesoriosActionPerformed

    private void txtidmecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidmecanicoActionPerformed
        // TODO add your handling code here:
        jTFidhabitacion.transferFocus();
    }//GEN-LAST:event_txtidmecanicoActionPerformed

    private void jTListadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTListadoMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTListadoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmreparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmreparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmreparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmreparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmreparacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnbuscaraccesorios;
    private javax.swing.JToggleButton btnbuscarclientes;
    private javax.swing.JToggleButton btnbuscarmeca;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBMODELO;
    private javax.swing.JComboBox<String> jCbFACTIRA;
    private javax.swing.JLabel jLNumero;
    private javax.swing.JLabel jLNumero1;
    private javax.swing.JLabel jLNumero2;
    private javax.swing.JLabel jLPiso;
    private javax.swing.JLabel jLPiso1;
    private javax.swing.JLabel jLPiso2;
    private javax.swing.JLabel jLPiso3;
    private javax.swing.JLabel jLPiso4;
    private javax.swing.JLabel jLRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFBuscar;
    private javax.swing.JTextField jTFgarantia;
    private javax.swing.JTextField jTFidhabitacion;
    private javax.swing.JTextField jTFmanodeobra;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JTable jTListado;
    private javax.swing.JButton jbreporte;
    public static javax.swing.JTextField txtaccesorios;
    public static javax.swing.JTextField txtclientes;
    public static javax.swing.JTextField txtidaccesorios;
    public static javax.swing.JTextField txtidcliente;
    public static javax.swing.JTextField txtidmecanico;
    public static javax.swing.JTextField txtmecanico;
    // End of variables declaration//GEN-END:variables
}
