-- MySQL Script generated by MySQL Workbench
-- Sun Sep 11 15:54:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Basemoto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Basemoto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Basemoto` DEFAULT CHARACTER SET latin1 ;
USE `Basemoto` ;

-- -----------------------------------------------------
-- Table `Basemoto`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Pais` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombrepa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombredepa` VARCHAR(45) NOT NULL,
  `barriodepa` VARCHAR(45) NOT NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  INDEX `fk_Departamento_Pais1_idx` (`idPais` ASC),
  CONSTRAINT `fk_Departamento_Pais1`
    FOREIGN KEY (`idPais`)
    REFERENCES `Basemoto`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nombrecli` VARCHAR(45) NOT NULL,
  `apellidocli` VARCHAR(45) NOT NULL,
  `direcioncli` VARCHAR(45) NOT NULL,
  `telefonocli` VARCHAR(45) NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_Departamento1_idx` (`idDepartamento` ASC),
  CONSTRAINT `fk_Clientes_Departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `Basemoto`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Mecanico` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Mecanico` (
  `idmecanico` INT NOT NULL AUTO_INCREMENT,
  `nombremeca` VARCHAR(45) NOT NULL,
  `apellidomeca` VARCHAR(45) NOT NULL,
  `direccionmeca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Tipoacceso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Tipoacceso` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Tipoacceso` (
  `idTipoacceso` INT NOT NULL AUTO_INCREMENT,
  `nombrea` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoacceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Estado` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombreestado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`marcas` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`marcas` (
  `idmarcas` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Modelo` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Modelo` (
  `idModelo` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  `cilindrada` INT NOT NULL,
  `chapa` VARCHAR(45) NOT NULL,
  `chasis` VARCHAR(45) NOT NULL,
  `idmarcas` INT NOT NULL,
  PRIMARY KEY (`idModelo`),
  INDEX `fk_Modelo_marcas1_idx` (`idmarcas` ASC),
  CONSTRAINT `fk_Modelo_marcas1`
    FOREIGN KEY (`idmarcas`)
    REFERENCES `Basemoto`.`marcas` (`idmarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = macce;


-- -----------------------------------------------------
-- Table `Basemoto`.`TipoFactura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`TipoFactura` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`TipoFactura` (
  `idTipoFactura` INT NOT NULL AUTO_INCREMENT,
  `nombrefac` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoFactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Accesorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Accesorios` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Accesorios` (
  `idAccesorios` INT NOT NULL AUTO_INCREMENT,
  `codigoaccesorios` VARCHAR(45) NOT NULL,
  `nombreacc` VARCHAR(45) NOT NULL,
  `marcaacc` VARCHAR(45) NOT NULL,
  `cantidadacc` INT NOT NULL,
  `precioacc` INT NOT NULL,
  PRIMARY KEY (`idAccesorios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Reparacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Reparacion` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Reparacion` (
  `idReparacion` INT NOT NULL AUTO_INCREMENT,
  `problema` VARCHAR(45) NOT NULL,
  `manodeobra` INT NOT NULL,
  `garantia` VARCHAR(45) NOT NULL,
  `idModelo` INT NOT NULL,
  `idmecanico` INT NOT NULL,
  `idClientes` INT NOT NULL,
  `idTipoFactura` INT NOT NULL,
  `idAccesorios` INT NOT NULL,
  PRIMARY KEY (`idReparacion`),
  INDEX `fk_Reparacion_Modelo1_idx` (`idModelo` ASC),
  INDEX `fk_Reparacion_Mecanico1_idx` (`idmecanico` ASC),
  INDEX `fk_Reparacion_Clientes1_idx` (`idClientes` ASC),
  INDEX `fk_Reparacion_TipoFactura1_idx` (`idTipoFactura` ASC),
  INDEX `fk_Reparacion_Accesorios1_idx` (`idAccesorios` ASC),
  CONSTRAINT `fk_Reparacion_Modelo1`
    FOREIGN KEY (`idModelo`)
    REFERENCES `Basemoto`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reparacion_Mecanico1`
    FOREIGN KEY (`idmecanico`)
    REFERENCES `Basemoto`.`Mecanico` (`idmecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reparacion_Clientes1`
    FOREIGN KEY (`idClientes`)
    REFERENCES `Basemoto`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reparacion_TipoFactura1`
    FOREIGN KEY (`idTipoFactura`)
    REFERENCES `Basemoto`.`TipoFactura` (`idTipoFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reparacion_Accesorios1`
    FOREIGN KEY (`idAccesorios`)
    REFERENCES `Basemoto`.`Accesorios` (`idAccesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`banco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`banco` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`banco` (
  `idbanco` INT NOT NULL AUTO_INCREMENT,
  `ruc` VARCHAR(45) NOT NULL,
  `descri` VARCHAR(45) NOT NULL,
  `direc` VARCHAR(45) NOT NULL,
  `telef` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`tarjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`tarjeta` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`tarjeta` (
  `idtarjeta` INT NOT NULL AUTO_INCREMENT,
  `descrii` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `emisor` VARCHAR(45) NOT NULL,
  `idbanco` INT NOT NULL,
  PRIMARY KEY (`idtarjeta`),
  INDEX `fk_tarjeta_banco1_idx` (`idbanco` ASC),
  CONSTRAINT `fk_tarjeta_banco1`
    FOREIGN KEY (`idbanco`)
    REFERENCES `Basemoto`.`banco` (`idbanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`TipoTrabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`TipoTrabajador` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`TipoTrabajador` (
  `idtipotrabajador` INT NOT NULL AUTO_INCREMENT,
  `nombretra` VARCHAR(45) NOT NULL,
  `apellidotra` VARCHAR(45) NOT NULL,
  `direciontra` VARCHAR(45) NOT NULL,
  `telefonotra` VARCHAR(45) NOT NULL,
  `Numerodocumento` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `idEstado` INT NOT NULL,
  `idTipoacceso` INT NOT NULL,
  `idDepartamento` INT NOT NULL,
  INDEX `fk_TipoTrabajador_Estado1_idx` (`idEstado` ASC),
  INDEX `fk_TipoTrabajador_Tipoacceso1_idx` (`idTipoacceso` ASC),
  INDEX `fk_TipoTrabajador_Departamento1_idx` (`idDepartamento` ASC),
  PRIMARY KEY (`idtipotrabajador`),
  CONSTRAINT `fk_TipoTrabajador_Estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `Basemoto`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TipoTrabajador_Tipoacceso1`
    FOREIGN KEY (`idTipoacceso`)
    REFERENCES `Basemoto`.`Tipoacceso` (`idTipoacceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TipoTrabajador_Departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `Basemoto`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Caja` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Caja` (
  `idCaja` INT NOT NULL AUTO_INCREMENT,
  `idClientes` INT NOT NULL,
  `idtipotrabajador` INT NOT NULL,
  `descri` VARCHAR(40) NOT NULL,
  `cant` INT NOT NULL,
  `precio` INT NOT NULL,
  `fechaventa` DATE NOT NULL,
  `iva` VARCHAR(45) NOT NULL,
  `subtotal` INT NOT NULL,
  `totalpago` INT NOT NULL,
  `idTipoFactura` INT NOT NULL,
  `idtarjeta` INT NOT NULL,
  `idAccesorios` INT NOT NULL,
  `idModelo` INT NOT NULL,
  PRIMARY KEY (`idCaja`),
  INDEX `fk_Caja_TipoFactura1_idx` (`idTipoFactura` ASC),
  INDEX `fk_Caja_tarjetas1_idx` (`idtarjeta` ASC),
  INDEX `fk_Caja_Accesorios1_idx` (`idAccesorios` ASC),
  INDEX `fk_Caja_Modelo1_idx` (`idModelo` ASC),
  INDEX `fk_Caja_Clientes1_idx` (`idClientes` ASC),
  INDEX `fk_Caja_TipoTrabajador1_idx` (`idtipotrabajador` ASC),
  CONSTRAINT `fk_Caja_TipoFactura1`
    FOREIGN KEY (`idTipoFactura`)
    REFERENCES `Basemoto`.`TipoFactura` (`idTipoFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caja_tarjetas1`
    FOREIGN KEY (`idtarjeta`)
    REFERENCES `Basemoto`.`tarjeta` (`idtarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caja_Accesorios1`
    FOREIGN KEY (`idAccesorios`)
    REFERENCES `Basemoto`.`Accesorios` (`idAccesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caja_Modelo1`
    FOREIGN KEY (`idModelo`)
    REFERENCES `Basemoto`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caja_Clientes1`
    FOREIGN KEY (`idClientes`)
    REFERENCES `Basemoto`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caja_TipoTrabajador1`
    FOREIGN KEY (`idtipotrabajador`)
    REFERENCES `Basemoto`.`TipoTrabajador` (`idtipotrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Arqueo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Arqueo` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Arqueo` (
  `idArqueo` INT NOT NULL AUTO_INCREMENT,
  `idtipotrabajador` INT NOT NULL,
  `monto_aper` INT NOT NULL,
  `fechaaper` TIMESTAMP NOT NULL,
  `montocierre` INT NOT NULL,
  `fechacierre` TIMESTAMP NULL,
  `totalrecaudado` INT NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idArqueo`),
  INDEX `fk_Arqueo_Estado1_idx` (`idEstado` ASC),
  INDEX `fk_Arqueo_TipoTrabajador1_idx` (`idtipotrabajador` ASC),
  CONSTRAINT `fk_Arqueo_Estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `Basemoto`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Arqueo_TipoTrabajador1`
    FOREIGN KEY (`idtipotrabajador`)
    REFERENCES `Basemoto`.`TipoTrabajador` (`idtipotrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Proovedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Proovedor` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Proovedor` (
  `idProovedor` INT NOT NULL AUTO_INCREMENT,
  `nombrepro` VARCHAR(45) NOT NULL,
  `telefonopro` VARCHAR(45) NOT NULL,
  `direccionpro` VARCHAR(45) NOT NULL,
  `rucpro` VARCHAR(45) NOT NULL,
  `fechaingresopro` DATE NOT NULL,
  `empresapro` VARCHAR(45) NOT NULL,
  `idDepartamento` INT NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idProovedor`),
  INDEX `fk_Proovedor_Departamento1_idx` (`idDepartamento` ASC),
  INDEX `fk_Proovedor_Estado1_idx` (`idEstado` ASC),
  CONSTRAINT `fk_Proovedor_Departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `Basemoto`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proovedor_Estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `Basemoto`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`pago` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`pago` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `preciodeproducto` INT NOT NULL,
  `iva` INT NOT NULL,
  `fechapago` DATE NOT NULL,
  `ruc` VARCHAR(45) NOT NULL,
  `idClientes` INT NOT NULL,
  `idAccesorios` INT NOT NULL,
  `idTipoFactura` INT NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_pago_Clientes1_idx` (`idClientes` ASC),
  INDEX `fk_pago_Accesorios1_idx` (`idAccesorios` ASC),
  INDEX `fk_pago_TipoFactura1_idx` (`idTipoFactura` ASC),
  CONSTRAINT `fk_pago_Clientes1`
    FOREIGN KEY (`idClientes`)
    REFERENCES `Basemoto`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_Accesorios1`
    FOREIGN KEY (`idAccesorios`)
    REFERENCES `Basemoto`.`Accesorios` (`idAccesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_TipoFactura1`
    FOREIGN KEY (`idTipoFactura`)
    REFERENCES `Basemoto`.`TipoFactura` (`idTipoFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`codigocliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`codigocliente` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`codigocliente` (
  `idClientes` INT NOT NULL,
  `codigo_cliente` VARCHAR(45) NOT NULL,
  INDEX `fk_codigocliente_Clientes1_idx` (`idClientes` ASC),
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `codigo_cliente_UNIQUE` (`codigo_cliente` ASC),
  CONSTRAINT `fk_codigocliente_Clientes1`
    FOREIGN KEY (`idClientes`)
    REFERENCES `Basemoto`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`llegada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`llegada` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`llegada` (
  `idllegada` INT NOT NULL AUTO_INCREMENT,
  `fechallega` DATE NOT NULL,
  `ordenllegada` VARCHAR(45) NOT NULL,
  `idModelo` INT NOT NULL,
  `idClientes` INT NOT NULL,
  `idmecanico` INT NOT NULL,
  PRIMARY KEY (`idllegada`),
  INDEX `fk_llegada_Modelo1_idx` (`idModelo` ASC),
  INDEX `fk_llegada_codigocliente1_idx` (`idClientes` ASC),
  INDEX `fk_llegada_Mecanico1_idx` (`idmecanico` ASC),
  CONSTRAINT `fk_llegada_Modelo1`
    FOREIGN KEY (`idModelo`)
    REFERENCES `Basemoto`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_llegada_codigocliente1`
    FOREIGN KEY (`idClientes`)
    REFERENCES `Basemoto`.`codigocliente` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_llegada_Mecanico1`
    FOREIGN KEY (`idmecanico`)
    REFERENCES `Basemoto`.`Mecanico` (`idmecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`ventas` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`ventas` (
  `idventas` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `idAccesorios` INT NOT NULL,
  `idClientes` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idventas`),
  INDEX `fk_ventas_Accesorios1_idx` (`idAccesorios` ASC),
  INDEX `fk_ventas_Clientes1_idx` (`idClientes` ASC),
  CONSTRAINT `fk_ventas_Accesorios1`
    FOREIGN KEY (`idAccesorios`)
    REFERENCES `Basemoto`.`Accesorios` (`idAccesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_Clientes1`
    FOREIGN KEY (`idClientes`)
    REFERENCES `Basemoto`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`reclamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`reclamos` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`reclamos` (
  `idreclamos` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecharecla` DATE NOT NULL,
  `idClientes` INT NOT NULL,
  `idModelo` INT NOT NULL,
  PRIMARY KEY (`idreclamos`),
  INDEX `fk_reclamos_Clientes1_idx` (`idClientes` ASC),
  INDEX `fk_reclamos_Modelo1_idx` (`idModelo` ASC),
  CONSTRAINT `fk_reclamos_Clientes1`
    FOREIGN KEY (`idClientes`)
    REFERENCES `Basemoto`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reclamos_Modelo1`
    FOREIGN KEY (`idModelo`)
    REFERENCES `Basemoto`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Sucursal` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_Sucursal_Departamento1_idx` (`idDepartamento` ASC),
  CONSTRAINT `fk_Sucursal_Departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `Basemoto`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`Stock` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`Stock` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `idAccesorios` INT NOT NULL,
  `cant` INT NOT NULL,
  PRIMARY KEY (`idSucursal`, `idAccesorios`),
  INDEX `fk_Sucursal_has_Accesorios_Accesorios1_idx` (`idAccesorios` ASC),
  INDEX `fk_Sucursal_has_Accesorios_Sucursal1_idx` (`idSucursal` ASC),
  CONSTRAINT `fk_Sucursal_has_Accesorios_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `Basemoto`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_has_Accesorios_Accesorios1`
    FOREIGN KEY (`idAccesorios`)
    REFERENCES `Basemoto`.`Accesorios` (`idAccesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`apertura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`apertura` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`apertura` (
  `idapertura` INT NOT NULL AUTO_INCREMENT,
  `idtipotrabajador` INT NOT NULL,
  `montoaper` VARCHAR(45) NOT NULL,
  `fechaaper` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idapertura`),
  INDEX `fk_apertura_TipoTrabajador1_idx` (`idtipotrabajador` ASC),
  CONSTRAINT `fk_apertura_TipoTrabajador1`
    FOREIGN KEY (`idtipotrabajador`)
    REFERENCES `Basemoto`.`TipoTrabajador` (`idtipotrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Basemoto`.`movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Basemoto`.`movimiento` ;

CREATE TABLE IF NOT EXISTS `Basemoto`.`movimiento` (
  `idmovi` INT NOT NULL AUTO_INCREMENT,
  `idtipotrabajador` INT NOT NULL,
  `monto` DOUBLE NOT NULL,
  `fechamovi` TIMESTAMP NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  `idapertura` INT NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idmovi`),
  INDEX `fk_movimiento_TipoTrabajador1_idx` (`idtipotrabajador` ASC),
  INDEX `fk_movimiento_apertura1_idx` (`idapertura` ASC),
  INDEX `fk_movimiento_Estado1_idx` (`idEstado` ASC),
  CONSTRAINT `fk_movimiento_TipoTrabajador1`
    FOREIGN KEY (`idtipotrabajador`)
    REFERENCES `Basemoto`.`TipoTrabajador` (`idtipotrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_apertura1`
    FOREIGN KEY (`idapertura`)
    REFERENCES `Basemoto`.`apertura` (`idapertura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_Estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `Basemoto`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
